[package]
name = "fp_server"
version = "2.0.1"
edition = "2021"

license = "GPL-3.0"
description = "A basic HTTP Server lib"
documentation = "https://docs.rs/fp_server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
